server {
    listen 9000;
    server_name localhost;
    
    root /var/www/html/softy-pinko-front-end;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    # Static files
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
